package com.engine.taskmanagement.task.activity.enums;

public enum TaskActivityType {
    TASK_CREATED,
    TASK_UPDATED,
    STATUS_CHANGED,
    ASSIGNEE_CHANGED,
    PRIORITY_CHANGED,
    TYPE_CHANGED,
    SEVERITY_CHANGED,
    COMMENT_ADDED,
    ACCEPTANCE_CRITERIA_ADDED,
    ACCEPTANCE_CRITERIA_UPDATED,
    ACCEPTANCE_CRITERIA_COMPLETED,
    TASK_BLOCKED,
    TASK_REOPENED,
    TASK_CANCELLED
}
