CREATE TABLE acceptance_criteria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6) NULL,
    task_id BIGINT NOT NULL,
    text VARCHAR(500) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_by_id BIGINT NULL,
    completed_at TIMESTAMP(6) NULL,
    completed_by_id BIGINT NULL,
    CONSTRAINT pk_acceptance_criteria PRIMARY KEY (id),
    CONSTRAINT fk_acceptance_criteria_task
        FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_acceptance_criteria_created_by
        FOREIGN KEY (created_by_id) REFERENCES users (id),
    CONSTRAINT fk_acceptance_criteria_completed_by
        FOREIGN KEY (completed_by_id) REFERENCES users (id)
);

CREATE INDEX idx_acceptance_criteria_task_id ON acceptance_criteria (task_id);
CREATE INDEX idx_acceptance_criteria_created_by_id ON acceptance_criteria (created_by_id);
CREATE INDEX idx_acceptance_criteria_completed_by_id ON acceptance_criteria (completed_by_id);
CREATE INDEX idx_acceptance_criteria_task_completed ON acceptance_criteria (task_id, completed);
