CREATE TABLE task_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6) NULL,
    task_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    body VARCHAR(2000) NOT NULL,
    CONSTRAINT pk_task_comments PRIMARY KEY (id),
    CONSTRAINT fk_task_comments_task
        FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_task_comments_author
        FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE INDEX idx_task_comments_task_id_deleted_at ON task_comments (task_id, deleted_at);
CREATE INDEX idx_task_comments_author_id ON task_comments (author_id);
CREATE INDEX idx_task_comments_type ON task_comments (type);
